"""
Budget Agent — zero AI calls.
Deterministically computes budget allocation and validates affordability.
Pure math: no LLM needed for arithmetic.
"""

from typing import Any, Dict
from tools.hotel_tool import hotel_tool


# Budget allocation weights (must sum to 1.0)
BUDGET_WEIGHTS = {
    "transport": 0.30,   # Biggest single cost: flights/trains
    "hotels":    0.35,   # Accommodation
    "activities": 0.15,  # Experiences
    "food":      0.15,   # Daily meals
    "buffer":    0.05,   # Emergency / tips / misc
}


async def budget_agent(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    LangGraph node: calculates budget breakdown, validates affordability
    against actual tool results, and flags overspend warnings.
    No LLM call — pure deterministic math.
    """
    try:
        budget = float(state.get("budget", 3000))
        travelers = int(state.get("num_travelers", 1))
        dates = state.get("travel_dates", {})
        
        # Check if budget is unlimited
        is_unlimited = budget >= 999999
        
        # Ensure hotels are fetched for budget calculations
        hotels = state.get("hotels", [])
        if not hotels:
            try:
                hotel_res = await hotel_tool(state)
                hotels = hotel_res.get("hotels", [])
                state = {**state, "hotels": hotels}
            except Exception as e:
                return {
                    "budget_breakdown": {},
                    "hotels": [],
                    "warnings": [f"Hotel tool error: {str(e)}"],
                    "execution_trace": ["budget_agent:hotel_error"],
                }

        transport = state.get("transport", {})
        activities = state.get("activities", [])

        # Compute trip duration
        try:
            from datetime import date
            start = date.fromisoformat(dates.get("start", "2025-06-01"))
            end = date.fromisoformat(dates.get("end", "2025-06-07"))
            num_nights = max((end - start).days, 1)
        except Exception:
            num_nights = 7  # fallback

        # Allocation (skip if unlimited budget)
        if is_unlimited:
            breakdown = {k: float('inf') for k in BUDGET_WEIGHTS.keys()}
        else:
            breakdown = {k: round(budget * w, 2) for k, w in BUDGET_WEIGHTS.items()}

        # Initialize a new list for warnings generated by this agent
        warnings = []
        
        # Initialize transport_cost and daily_food_per_person
        transport_cost = 0
        daily_food_per_person = 0

        # Validate only if budget is not unlimited
        if not is_unlimited:
            # Validate: cheapest hotel × nights vs. allocation
            if hotels:
                cheapest_hotel = min(hotels, key=lambda h: h["price_per_night"])
                hotel_needed = cheapest_hotel["price_per_night"] * num_nights
                if hotel_needed > breakdown["hotels"]:
                    overage = hotel_needed - breakdown["hotels"]
                    warnings.append(
                        f"Hotel budget short by ${overage:.0f}. "
                        f"Cheapest option: ${cheapest_hotel['price_per_night']}/night × {num_nights} nights = ${hotel_needed:.0f}"
                    )

            # Validate: transport cost vs. allocation
            if transport.get("recommended"):
                transport_cost = transport["recommended"].get("total_cost", 0)
                if transport_cost > breakdown["transport"]:
                    overage = transport_cost - breakdown["transport"]
                    warnings.append(
                        f"Transport budget short by ${overage:.0f}. "
                        f"Recommended option costs ${transport_cost:.0f}."
                    )

            # Per-person daily food estimate
            daily_food_per_person = breakdown["food"] / (num_nights * travelers)
        else:
            # For unlimited budgets, set reasonable defaults
            daily_food_per_person = 100.0  # Reasonable daily food estimate
            if transport.get("recommended"):
                transport_cost = transport["recommended"].get("total_cost", 0)

        budget_breakdown = {
            **breakdown,
            "num_nights": num_nights,
            "num_travelers": travelers,
            "daily_food_budget_per_person": round(daily_food_per_person, 2),
            "total_committed": round(
                transport_cost + (hotels[0]["price_per_night"] * num_nights if hotels else 0),
                2,
            ),
            "remaining_flex": round(
                budget - transport_cost - (hotels[0]["price_per_night"] * num_nights if hotels else 0),
                2,
            ),
        }

        return {
            "budget_breakdown": budget_breakdown,
            "hotels": hotels,
            "warnings": warnings,
            "execution_trace": ["budget_agent"],
        }
    except Exception as e:
        return {
            "budget_breakdown": {},
            "hotels": [],
            "warnings": [f"Budget agent error: {str(e)}"],
            "execution_trace": ["budget_agent:error"],
        }

